//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslationHelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DontLoadStringIfRomajiPercent {
            get {
                return ((bool)(this["DontLoadStringIfRomajiPercent"]));
            }
            set {
                this["DontLoadStringIfRomajiPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("90")]
        public int DontLoadStringIfRomajiPercentNumber {
            get {
                return ((int)(this["DontLoadStringIfRomajiPercentNumber"]));
            }
            set {
                this["DontLoadStringIfRomajiPercentNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AutotranslationForSimular {
            get {
                return ((bool)(this["AutotranslationForSimular"]));
            }
            set {
                this["AutotranslationForSimular"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsFullComprasionDBloadEnabled {
            get {
                return ((bool)(this["IsFullComprasionDBloadEnabled"]));
            }
            set {
                this["IsFullComprasionDBloadEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://translate.google.com/?ie=UTF-8&op=translate&sl=auto&tl=en&text={text}")]
        public string WebTranslationLink {
            get {
                return ((string)(this["WebTranslationLink"]));
            }
            set {
                this["WebTranslationLink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Japanese jp")]
        public string OnlineTranslationSourceLanguage {
            get {
                return ((string)(this["OnlineTranslationSourceLanguage"]));
            }
            set {
                this["OnlineTranslationSourceLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("English en")]
        public string OnlineTranslationTargetLanguage {
            get {
                return ((string)(this["OnlineTranslationTargetLanguage"]));
            }
            set {
                this["OnlineTranslationTargetLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool THdebug {
            get {
                return ((bool)(this["THdebug"]));
            }
            set {
                this["THdebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsTranslationHelperWasClosed {
            get {
                return ((bool)(this["IsTranslationHelperWasClosed"]));
            }
            set {
                this["IsTranslationHelperWasClosed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int THOptionLineCharLimit {
            get {
                return ((int)(this["THOptionLineCharLimit"]));
            }
            set {
                this["THOptionLineCharLimit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20")]
        public int THSavedSearchQueriesReplacersCount {
            get {
                return ((int)(this["THSavedSearchQueriesReplacersCount"]));
            }
            set {
                this["THSavedSearchQueriesReplacersCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string THSelectedGameDir {
            get {
                return ((string)(this["THSelectedGameDir"]));
            }
            set {
                this["THSelectedGameDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string THSelectedDir {
            get {
                return ((string)(this["THSelectedDir"]));
            }
            set {
                this["THSelectedDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public string RPGMTransPatchVersion {
            get {
                return ((string)(this["RPGMTransPatchVersion"]));
            }
            set {
                this["RPGMTransPatchVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string THSelectedSourceType {
            get {
                return ((string)(this["THSelectedSourceType"]));
            }
            set {
                this["THSelectedSourceType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int THFilesListSelectedIndex {
            get {
                return ((int)(this["THFilesListSelectedIndex"]));
            }
            set {
                this["THFilesListSelectedIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string THTranslationCachePath {
            get {
                return ((string)(this["THTranslationCachePath"]));
            }
            set {
                this["THTranslationCachePath"] = value;
            }
        }
        
        /// <summary>
        /// Newline symbol specified for opened project
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ProjectNewLineSymbol {
            get {
                return ((string)(this["ProjectNewLineSymbol"]));
            }
            set {
                this["ProjectNewLineSymbol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string THProjectWorkDir {
            get {
                return ((string)(this["THProjectWorkDir"]));
            }
            set {
                this["THProjectWorkDir"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool THAutoSetSameTranslationForSimularIsBusy {
            get {
                return ((bool)(this["THAutoSetSameTranslationForSimularIsBusy"]));
            }
            set {
                this["THAutoSetSameTranslationForSimularIsBusy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int OnlineTranslationCacheUseCount {
            get {
                return ((int)(this["OnlineTranslationCacheUseCount"]));
            }
            set {
                this["OnlineTranslationCacheUseCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DGVSelectedRowIndex {
            get {
                return ((int)(this["DGVSelectedRowIndex"]));
            }
            set {
                this["DGVSelectedRowIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DGVSelectedRowRealIndex {
            get {
                return ((int)(this["DGVSelectedRowRealIndex"]));
            }
            set {
                this["DGVSelectedRowRealIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int DGVSelectedColumnIndex {
            get {
                return ((int)(this["DGVSelectedColumnIndex"]));
            }
            set {
                this["DGVSelectedColumnIndex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ProjectIsOpened {
            get {
                return ((bool)(this["ProjectIsOpened"]));
            }
            set {
                this["ProjectIsOpened"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DGVCellInEditMode {
            get {
                return ((bool)(this["DGVCellInEditMode"]));
            }
            set {
                this["DGVCellInEditMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DebugMode {
            get {
                return ((bool)(this["DebugMode"]));
            }
            set {
                this["DebugMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DBTryToCheckLinesOfEachMultilineValue {
            get {
                return ((bool)(this["DBTryToCheckLinesOfEachMultilineValue"]));
            }
            set {
                this["DBTryToCheckLinesOfEachMultilineValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ApplyFixesOnTranslation {
            get {
                return ((bool)(this["ApplyFixesOnTranslation"]));
            }
            set {
                this["ApplyFixesOnTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UseAllDBFilesForOnlineTranslationForAll {
            get {
                return ((bool)(this["UseAllDBFilesForOnlineTranslationForAll"]));
            }
            set {
                this["UseAllDBFilesForOnlineTranslationForAll"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DBCompression {
            get {
                return ((bool)(this["DBCompression"]));
            }
            set {
                this["DBCompression"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DontLoadStringIfRomajiPercentForOpen {
            get {
                return ((bool)(this["DontLoadStringIfRomajiPercentForOpen"]));
            }
            set {
                this["DontLoadStringIfRomajiPercentForOpen"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DontLoadStringIfRomajiPercentForTranslation {
            get {
                return ((bool)(this["DontLoadStringIfRomajiPercentForTranslation"]));
            }
            set {
                this["DontLoadStringIfRomajiPercentForTranslation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"XML (none)\"")]
        public string DBCompressionExt {
            get {
                return ((string)(this["DBCompressionExt"]));
            }
            set {
                this["DBCompressionExt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableTranslationCache {
            get {
                return ((bool)(this["EnableTranslationCache"]));
            }
            set {
                this["EnableTranslationCache"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int DBAutoSaveTimeout {
            get {
                return ((int)(this["DBAutoSaveTimeout"]));
            }
            set {
                this["DBAutoSaveTimeout"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool EnableDBAutosave {
            get {
                return ((bool)(this["EnableDBAutosave"]));
            }
            set {
                this["EnableDBAutosave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationStartupPath {
            get {
                return ((string)(this["ApplicationStartupPath"]));
            }
            set {
                this["ApplicationStartupPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ApplicationProductName {
            get {
                return ((string)(this["ApplicationProductName"]));
            }
            set {
                this["ApplicationProductName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\")]
        public string NewLine {
            get {
                return ((string)(this["NewLine"]));
            }
            set {
                this["NewLine"] = value;
            }
        }
    }
}
